### ISSUE TITLE
Clear and neat code , I have a small note

### ISSUE THREAD

**Issue by meyadd** [itemah26/HackYourFuture-JavaScript2-HWks#5]
when you type any text in the field of repository name then click "Show Contributers" button or "Go" button, program will show two alerts instead of one
the problem is in line 70 in your code:
```
else if (xmlHttp.readyState != 4 && xmlHttp.status == 404)
               alert('Check your input...');
```
you display the alert when  xmlHttp.readyState=2 and xmlHttp.readyState = 3 with xmlHttp.status == 404
to fix this issue you should check the status after the client has recieved the response from server, so:
```
else if (xmlHttp.readyState== 4 && xmlHttp.status == 404)
               alert('....')
```

**Comment by itemah26** [comment]
Thanks Eyad, I will fix it like you said.
